version: "3.1"
services:
  reverseproxy:
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    container_name: reverseproxy
    networks:
      - docker-network

  site1:
    build:
      context: ./site1
      dockerfile: Dockerfile
    container_name: site1
    ports:
      - 8080:8080
    networks:
      docker-network:
        aliases:
          - site1

  site2:
    build:
      context: ./site2
      dockerfile: Dockerfile
    container_name: site2
    ports:
      - 8081:8081
    networks:
      docker-network:
        aliases:
          - site2

networks:
  docker-network:
    name: docker-network
